### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by soderlind** [catherineriver/sanity-plugin-generate-ogimage#1]
Hi,

Following the [README](https://github.com/catherineriver/sanity-plugin-generate-ogimage#installation), running `npm install sanity-plugin-generate-ogimage`fails with a 404

Doing `npm install @catherineriver/sanity-plugin-generate-ogimage` works fine, just a npm warn - `npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.`

**Comment by catherineriver** [comment]
Hi,

Thank you for pointing that out. I've fixed the issue in the README.
